language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - python3 bin/bootstrap-buildout.py
  - bin/buildout
script:
  - bin/py.test --cov=grader -v grader/
